# Generated by Django 4.0.3 on 2022-04-02 09:13

from django.db import migrations, models
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', validators=[videos.validators.validate_file_extension], verbose_name='Video (Only .mp4)'),
        ),
    ]
