# Generated by Django 4.0.3 on 2022-04-05 17:00

from django.db import migrations, models
import django.db.models.deletion
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to='media/', validators=[videos.validators.validate_file_extension], verbose_name='Video (Only .mp4)'),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='Name:')),
                ('comment_content', models.CharField(max_length=250, verbose_name='Comment')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video', verbose_name='Article')),
            ],
        ),
    ]
