# Generated by Django 4.0.3 on 2022-04-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_video_file_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_date']},
        ),
    ]
